import type { LadwpEzSaveWorkflowField } from "./types";

export const LADWP_EZ_SAVE_PROGRAM_ID = "ladwp_ez_save";

export const LADWP_EZ_SAVE_WORKFLOW = {
  programId: LADWP_EZ_SAVE_PROGRAM_ID,
  displayName: "LADWP EZ-SAVE",
  utility: "LADWP",
  state: "CA",
  city: "Los Angeles",
  programType: "utility_discount",
  supportedStatus: "mvp_supported",
  sourceUrls: [
    "https://www.ladwp.com/residential-services/assistance-programs/ez-save-program",
    "https://www.ladwp.com/sites/default/files/2023-10/2023_EZ-SAVE_Application_and_Information_05_0.pdf",
  ],
  applicationUrl:
    "https://www.ladwp.com/residential-services/assistance-programs/ez-save-program",
  pdfApplicationUrl:
    "https://www.ladwp.com/sites/default/files/2023-10/2023_EZ-SAVE_Application_and_Information_05_0.pdf",
  mailAddress: [
    "LADWP",
    "EZ-SAVE Program, Room L63",
    "PO Box 515407",
    "Los Angeles, CA 90051-6707",
  ],
  faxNumber: "(213) 241-1465",
  emailSubmissionAddress: null,
  emailSubmissionNote:
    "The official LADWP EZ-SAVE packet lists online, fax, and mail submission. It does not list an email submission address.",
  contactPhone: "1-800-DIAL-DWP",
  lastVerifiedDate: null,
  annualReviewNote:
    "Income thresholds and program rules should be reviewed annually.",
  workflowSummary:
    "LADWP EZ-SAVE is an income-qualified utility bill discount program for LADWP residential customers. This app estimates eligibility, prepares an application draft, and guides the user to the fastest official submission path. Lower monthly bills can make it easier for customers to stay current, but this app does not guarantee approval or shutoff protection and does not submit automatically.",
  requiredFields: [
    "utility_provider",
    "is_ladwp_customer",
    "zip_code",
    "first_name",
    "last_name",
    "service_address_street_number",
    "service_address_street_name",
    "household_total",
    "household_adults",
    "household_children",
    "annual_gross_household_income",
    "is_customer_of_record",
    "is_primary_residence",
    "claimed_as_dependent",
    "new_application_or_renewal",
    "consent_to_prepare_application",
    "user_certifies_review_required",
  ],
  optionalFields: [
    "middle_initial",
    "apartment_number",
    "phone",
    "mobile_phone",
    "email",
    "account_number",
    "monthly_bill_amount",
    "past_due_status",
  ],
  sensitiveFieldsBlocklist: [
    "SSN",
    "bank account",
    "government ID",
    "proof of income upload",
    "raw income document storage",
    "immigration status",
    "medical records",
    "signature image",
  ],
  resultLanguageTemplates: {
    likelyEligible:
      "Based on your household size and income, you may qualify for LADWP EZ-SAVE. We'll prepare your application draft so you can review it before applying.",
    possiblyEligibleNeedsReview:
      "Some answers need review before we can give a stronger estimate. You can still prepare a draft and compare it with LADWP's official instructions.",
    unlikelyEligible:
      "Based on the income you entered, you may be above LADWP's current EZ-SAVE income limit. You can still review LADWP's official page or check other LADWP programs.",
    notLadwp:
      "This first version supports LADWP customers only. We'll add more utilities later.",
    customerOfRecordIssue:
      "EZ-SAVE generally requires the applicant to be the LADWP customer of record. If the bill is not in your name, review LADWP's official instructions before applying.",
    dependentIssue:
      "EZ-SAVE applicants cannot be claimed as a dependent on another person's tax return. Review this before applying.",
    primaryResidenceIssue:
      "EZ-SAVE is intended for the customer's permanent, primary residence.",
    ampLikePastDueNote:
      "If your bill is past due, review LADWP payment assistance options after checking EZ-SAVE. EZ-SAVE may lower future bills, but it is not the same as a shutoff hold or payment arrangement.",
    privacyDisclaimer:
      "We use this information to estimate EZ-SAVE eligibility and prepare your application draft. Review all answers before applying. Do not upload income documents or sensitive IDs.",
    notGuaranteeDisclaimer:
      "Review these answers before applying. This app does not guarantee approval.",
    noIncomeProof:
      "No proof of income is needed to apply, but LADWP may verify eligibility later.",
    signatureReminder: "Sign before submitting.",
  },
  handoffOptions: [
    {
      key: "online",
      title: "Online application",
      copy: "Fastest if you have an LADWP online account.",
      buttonLabel: "Open LADWP application",
    },
    {
      key: "pdf",
      title: "Filled PDF packet",
      copy: "Download your completed draft. Review it, sign it, then submit to LADWP.",
      buttonLabel: "Download filled EZ-SAVE PDF",
    },
    {
      key: "mail_fax",
      title: "Mail or fax",
      copy: "Only use this after reviewing and signing your application.",
      buttonLabel: "View mail/fax instructions",
    },
    {
      key: "email_draft",
      title: "Email draft",
      copy: "Download the packet and open a prewritten email draft. Attach the signed PDF before sending.",
      buttonLabel: "Prepare email draft",
    },
  ],
  checklistItems: [
    "Your LADWP bill or online account access",
    "Household size, adults, and children",
    "Combined gross annual household income",
    "Service address",
    "Phone number LADWP can use if they need to reach you",
    "Signature before submitting",
  ],
  extensionOrPartnerFutureNote:
    "A future browser extension or official partner integration can consume the ApplicationDraft payload after user review and consent. No automatic submission is allowed in the MVP.",
} as const;

export const LADWP_EZ_SAVE_FIELDS: LadwpEzSaveWorkflowField[] = [
  {
    fieldKey: "utility_provider",
    label: "Utility provider",
    type: "select",
    required: true,
    allowedValues: ["LADWP", "Other"],
    userHelpText: "This first version prepares LADWP EZ-SAVE only.",
    sourcePriority: ["user_answer", "uploaded_bill", "manual_edit"],
    canLlmFill: true,
    requiresUserConfirmation: true,
    validation: "Must be LADWP for this workflow.",
  },
  {
    fieldKey: "is_ladwp_customer",
    label: "LADWP residential customer",
    type: "boolean",
    required: true,
    userHelpText: "Choose yes if this is an LADWP residential account for your home.",
    sourcePriority: ["user_answer", "uploaded_bill", "manual_edit"],
    canLlmFill: true,
    requiresUserConfirmation: true,
    validation: "Boolean yes/no.",
  },
  {
    fieldKey: "zip_code",
    label: "ZIP code",
    type: "text",
    required: true,
    userHelpText: "Use the ZIP code where LADWP provides service, not a separate mailing address.",
    sourcePriority: ["user_answer", "uploaded_bill", "manual_edit"],
    canLlmFill: true,
    requiresUserConfirmation: true,
    validation: "Five-digit ZIP code.",
  },
  {
    fieldKey: "first_name",
    label: "First name",
    type: "text",
    required: true,
    userHelpText: "Use the first name of the person whose name is on the LADWP account.",
    sourcePriority: ["user_answer", "manual_edit"],
    canLlmFill: false,
    requiresUserConfirmation: true,
    validation: "Non-empty text.",
  },
  {
    fieldKey: "last_name",
    label: "Last name",
    type: "text",
    required: true,
    userHelpText: "Use the last name of the person whose name is on the LADWP account.",
    sourcePriority: ["user_answer", "manual_edit"],
    canLlmFill: false,
    requiresUserConfirmation: true,
    validation: "Non-empty text.",
  },
  {
    fieldKey: "middle_initial",
    label: "Middle initial",
    type: "text",
    required: false,
    userHelpText: "Optional middle initial for the LADWP customer of record.",
    sourcePriority: ["user_answer", "manual_edit"],
    canLlmFill: false,
    requiresUserConfirmation: true,
    validation: "One-character text if provided.",
  },
  {
    fieldKey: "service_address_street_number",
    label: "Street number",
    type: "text",
    required: true,
    userHelpText: "Use the street number for the home receiving LADWP service.",
    sourcePriority: ["user_answer", "uploaded_bill", "manual_edit"],
    canLlmFill: true,
    requiresUserConfirmation: true,
    validation: "Non-empty text.",
  },
  {
    fieldKey: "service_address_street_name",
    label: "Street name",
    type: "text",
    required: true,
    userHelpText: "Use the street name for the home receiving LADWP service.",
    sourcePriority: ["user_answer", "uploaded_bill", "manual_edit"],
    canLlmFill: true,
    requiresUserConfirmation: true,
    validation: "Non-empty text.",
  },
  {
    fieldKey: "apartment_number",
    label: "Apartment number",
    type: "text",
    required: false,
    userHelpText: "Add this if LADWP uses an apartment, unit, or space number for the service address.",
    sourcePriority: ["user_answer", "uploaded_bill", "manual_edit"],
    canLlmFill: true,
    requiresUserConfirmation: true,
    validation: "Text if provided.",
  },
  {
    fieldKey: "phone",
    label: "Home telephone",
    type: "text",
    required: false,
    recommended: true,
    userHelpText: "Recommended so LADWP can reach you if they need to review the application.",
    sourcePriority: ["user_answer", "manual_edit"],
    canLlmFill: false,
    requiresUserConfirmation: true,
    validation: "Phone text if provided.",
  },
  {
    fieldKey: "mobile_phone",
    label: "Mobile telephone",
    type: "text",
    required: false,
    userHelpText: "Optional. Add a mobile number if this is the easiest way for LADWP to reach you.",
    sourcePriority: ["user_answer", "manual_edit"],
    canLlmFill: false,
    requiresUserConfirmation: true,
    validation: "Phone text if provided.",
  },
  {
    fieldKey: "household_total",
    label: "Household total",
    type: "number",
    required: true,
    userHelpText: "Count everyone who lives in the home, including children and relatives.",
    sourcePriority: ["user_answer", "manual_edit"],
    canLlmFill: false,
    requiresUserConfirmation: true,
    validation: "Whole number greater than zero.",
  },
  {
    fieldKey: "household_adults",
    label: "Adults",
    type: "number",
    required: true,
    userHelpText: "Count household members age 18 or older.",
    sourcePriority: ["user_answer", "manual_edit"],
    canLlmFill: false,
    requiresUserConfirmation: true,
    validation: "Whole number zero or greater.",
  },
  {
    fieldKey: "household_children",
    label: "Children",
    type: "number",
    required: true,
    userHelpText: "Count household members under age 18.",
    sourcePriority: ["user_answer", "manual_edit"],
    canLlmFill: false,
    requiresUserConfirmation: true,
    validation: "Whole number zero or greater.",
  },
  {
    fieldKey: "annual_gross_household_income",
    label: "Combined gross annual household income",
    type: "number",
    required: true,
    userHelpText: "Use the household's yearly income before taxes. No proof of income is needed with the application.",
    sourcePriority: ["user_answer", "manual_edit"],
    canLlmFill: false,
    requiresUserConfirmation: true,
    validation: "Non-negative annual income.",
  },
  {
    fieldKey: "is_customer_of_record",
    label: "Customer of record",
    type: "boolean",
    required: true,
    userHelpText: "The customer of record is the person listed on the LADWP account or bill.",
    sourcePriority: ["user_answer", "uploaded_bill", "manual_edit"],
    canLlmFill: true,
    requiresUserConfirmation: true,
    validation: "Boolean yes/no.",
  },
  {
    fieldKey: "is_primary_residence",
    label: "Primary residence",
    type: "boolean",
    required: true,
    userHelpText: "This should be the home where you live most of the time, not a second home or business address.",
    sourcePriority: ["user_answer", "manual_edit"],
    canLlmFill: false,
    requiresUserConfirmation: true,
    validation: "Boolean yes/no.",
  },
  {
    fieldKey: "claimed_as_dependent",
    label: "Claimed as dependent",
    type: "boolean",
    required: true,
    userHelpText: "Answer yes if another person can list you as a dependent on their tax return.",
    sourcePriority: ["user_answer", "manual_edit"],
    canLlmFill: false,
    requiresUserConfirmation: true,
    validation: "Boolean yes/no.",
  },
  {
    fieldKey: "new_application_or_renewal",
    label: "New application or renewal",
    type: "select",
    required: true,
    allowedValues: ["new_application", "renewal"],
    userHelpText: "Choose renewal only if you are renewing an existing EZ-SAVE enrollment.",
    sourcePriority: ["user_answer", "manual_edit"],
    canLlmFill: false,
    requiresUserConfirmation: true,
    validation: "Must be new_application or renewal.",
  },
  {
    fieldKey: "email",
    label: "Email",
    type: "text",
    required: false,
    userHelpText: "Optional. Use this for reminders or a copy of your application draft.",
    sourcePriority: ["user_answer", "manual_edit"],
    canLlmFill: false,
    requiresUserConfirmation: true,
    validation: "Email text if provided.",
  },
  {
    fieldKey: "account_number",
    label: "LADWP account number",
    type: "text",
    required: false,
    userHelpText: "Only enter this if you want it included in your application draft. It is usually printed near the top of the LADWP bill. We do not need your SSN.",
    sourcePriority: ["user_answer", "uploaded_bill", "manual_edit"],
    canLlmFill: false,
    requiresUserConfirmation: true,
    validation: "Text if explicitly provided.",
  },
  {
    fieldKey: "monthly_bill_amount",
    label: "Monthly bill amount",
    type: "number",
    required: false,
    userHelpText: "Optional. Enter your typical monthly bill to help compare the discount against what you usually pay.",
    sourcePriority: ["user_answer", "uploaded_bill", "manual_edit"],
    canLlmFill: true,
    requiresUserConfirmation: true,
    validation: "Non-negative number if provided.",
  },
  {
    fieldKey: "past_due_status",
    label: "Bill is past due",
    type: "boolean",
    required: false,
    userHelpText: "Optional. If the bill is already past due, you may also want LADWP payment assistance information.",
    sourcePriority: ["user_answer", "uploaded_bill", "manual_edit"],
    canLlmFill: true,
    requiresUserConfirmation: true,
    validation: "Boolean yes/no if provided.",
  },
  {
    fieldKey: "consent_to_prepare_application",
    label: "Consent to prepare draft",
    type: "boolean",
    required: true,
    userHelpText: "Required so we can turn your answers into a filled application draft for your review.",
    sourcePriority: ["user_answer", "manual_edit"],
    canLlmFill: false,
    requiresUserConfirmation: true,
    validation: "Must be true to generate a draft.",
  },
  {
    fieldKey: "user_certifies_review_required",
    label: "Review required",
    type: "boolean",
    required: true,
    userHelpText: "You must review all answers before applying to LADWP.",
    sourcePriority: ["user_answer", "manual_edit"],
    canLlmFill: false,
    requiresUserConfirmation: true,
    validation: "Must be true to continue.",
  },
];

export function getLadwpEzSaveField(fieldKey: string) {
  return LADWP_EZ_SAVE_FIELDS.find((field) => field.fieldKey === fieldKey);
}
